services:
  postgres:
    image: postgres:16-alpine
    container_name: barbearia-postgres
    restart: always
    environment:
      POSTGRES_USER: barbearia
      POSTGRES_PASSWORD: barbearia01
      POSTGRES_DB: barbearia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: